### ISSUE TITLE
Jmx Exports for Workers

### ISSUE THREAD

**Issue by gauravmohta** [trinodb/charts#224]
The current helm chart has jmx exporter available only for coordinator and the worker pods do not have jmx exports. Could you please add the jmx exports for workers as well?

**Comment by nineinchnick** [comment]
We might not need separate JMX configuration for the coordinator and workers. I don't get the second question. We already integrate with service monitors for the Prometheus operator, let's continue using that.

**Comment by sdaberdaku** [comment]
The service monitor will get the metrics from the service, which will act as "load balancer" for the workers. I think we need to scrape the Pods individually. Does this make sense?

**Comment by nineinchnick** [comment]
Sure, we'll need a test for this setup anyway.

**Comment by sdaberdaku** [comment]
I think we should have separate JMX configurations for coordinator and workers for the following reasons:
- One might want to enable JMX Export only on the coordinator and ignore the worker specific metrics;
- In the worker JMX configuration we might want to set `includeObjectNames` or `excludeObjectNames` or `rules` differently from the coordinator (maybe on the worker we only want the JVM metrics and nothing more, while on the coordinator we want the specific Trino metrics).

**Comment by sdaberdaku** [comment]
After some reading I realized that my previous comment regarding the Service Monitor scraping only one Pod was wrong. 
https://github.com/prometheus-operator/prometheus-operator/issues/3119

It turns out that a ServiceMonitor will "scrape all pods behind the service, because the Service maintains an Endpoints object. That's where Prometheus discovers the targets from." 

However, since it does not make sense to have a Service for workers, I would go on and add a PodMonitor only for worker pods.

I also extended the existing jmx tests, I will shortly submit a new PR for this feature.
